name: smart_assistant_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
        sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^8.0.0
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.0 
  http: ^1.3.0 # تعامل مع Apis
  dartz: ^0.10.0 # سماح للفانكشن إرجاع اكتر من نوع 
  lottie: ^3.2.0 # لإضافة رسوم متحركة بتنسيق Lottie، مما يضفي لمسة جمالية وتفاعلية للتطبيق.
  percent_indicator: ^4.2.5
  google_nav_bar: ^5.0.7
  connectivity_plus: ^5.0.1
  skeletonizer: ^1.3.0 # لإعطاء تصميم لشاشات تحميل البيانات، مما يحسن تجربة المستخدم أثناء انتظار تحميل المحتوى.
  sidebarx: ^0.17.2
  equatable: ^2.0.8
  flutter_zoom_drawer: ^3.0.0
  path_provider: ^2.1.3
  open_file: ^3.3.3
  permission_handler: ^10.4.4  # للأذونات في Android
  url_launcher: ^6.0.0
  webview_flutter: ^4.5.2
  platform_file: ^0.1.0
  file_picker: ^8.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.5.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
    - assets/icons/
  fonts:
    - family: tajawal
      fonts:
      - asset: assets/fonts/ElMessiri-Regular.ttf
    - family: Gulzar
      fonts:
      - asset: assets/fonts/Gulzar-Regular.ttf
flutter_assets:
  assets_path: assets/
  output_path: lib/core/assets
  filename: app_assets.dart